import Navbar from "./components/Navbar";
import NotFound from "./components/NotFound";
import Login from "./components/heroSection/Login";
import Register from "./components/heroSection/Register";
import HeroSection from "./components/heroSection/HeroSection";
import HomeSection from "./components/homeSection/HomeSection";
import PrivateRoute from "./components/privateRoute/PrivateRoute";
import PreventRoute from "./components/privateRoute/PreventRoute";
import PageLaoding from "./components/PageLaoding";
import MyAccount from "./components/account/MyAccount";
import AddFriend from "./components/friendSection/AddFriend";
import ManageFriend from "./components/friendSection/ManageFriend";
import { useFirebaseContext } from "./contexts/FirebaseContext";
import {
  Avatar,
  Button,
  IconButton,
  FormControl,
  FormLabel,
  useDisclosure,
  Input,
  InputGroup,
  InputRightElement,
  Center,
  Container,
  Stack,
  Text,
  VStack,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  useToast,
  Image,
  HStack,
  Tooltip,
  Box,
  Link,
  SimpleGrid,
  Flex,
  StackDivider,
  Tag,
  Tabs,
  Tab,
  TabList,
  TabPanels,
  TabPanel,
  useColorModeValue,
  Heading,
  createIcon,
  Checkbox,
  Textarea,
  Collapse,
  Icon,
  Popover,
  PopoverTrigger,
  PopoverContent,
  useBreakpointValue,
  Menu,
  MenuButton,
  MenuList,
  MenuDivider,
  MenuItem,
  Divider,
} from "@chakra-ui/react";

import { FaRegEdit, FaCheck } from "react-icons/fa";
import {
  IoCloudUploadOutline,
  IoCopyOutline,
  IoPersonAdd,
  IoSearchOutline,
  IoPersonRemoveSharp,
  IoBuild,
  IoEyeOff,
  IoEye,
  IoMenu,
  IoClose,
  IoChevronDown,
  IoChevronForward,
  IoCheckmarkOutline,
} from "react-icons/io5";

const Pages = {
  Navbar,
  NotFound,
  Login,
  Register,
  HeroSection,
  HomeSection,
  PrivateRoute,
  PreventRoute,
  PageLaoding,
  MyAccount,
  useFirebaseContext,
  AddFriend,
  ManageFriend,
};

const Chakra = {
  Avatar,
  Button,
  IconButton,
  FormControl,
  FormLabel,
  useDisclosure,
  Input,
  InputGroup,
  InputRightElement,
  Center,
  Container,
  Stack,
  Text,
  VStack,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  StackDivider,
  ModalOverlay,
  useToast,
  Image,
  HStack,
  Tooltip,
  Box,
  Link,
  SimpleGrid,
  Flex,
  Tag,
  Tabs,
  Tab,
  TabList,
  TabPanels,
  TabPanel,
  useColorModeValue,
  Heading,
  createIcon,
  Checkbox,
  Textarea,
  Collapse,
  Icon,
  Popover,
  PopoverTrigger,
  PopoverContent,
  useBreakpointValue,
  Menu,
  MenuButton,
  MenuList,
  MenuDivider,
  MenuItem,
  Divider,
};

const icons = {
  FaRegEdit,
  FaCheck,
  IoCloudUploadOutline,
  IoCopyOutline,
  IoPersonAdd,
  IoSearchOutline,
  IoPersonRemoveSharp,
  IoBuild,
  IoEyeOff,
  IoEye,
  IoMenu,
  IoClose,
  IoChevronDown,
  IoChevronForward,
  IoCheckmarkOutline,
};

const Contexts = {
  useFirebaseContext,
};

export { Pages, Contexts, Chakra, icons };
